jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest

    variables:
      - name: DOTNET_VERSION
        value: 7.0.x

    steps:
      - task: UseDotNet@2
        displayName: 'Use dotnet $(DOTNET_VERSION)'
        inputs:
          packageType: 'sdk'
          version: '$(DOTNET_VERSION)'

      - task: DotNetCoreCLI@2
        displayName: 'Restore solution'
        inputs:
          command: 'restore'
          projects: '**/*.sln'

      - task: DotNetCoreCLI@2
        displayName: 'Build solution'
        inputs:
          command: 'build'